import os
import glob
import secrets
import textwrap
from flask import Flask, request, jsonify, render_template, Response
import yaml

app = Flask(__name__)

RECIPES_DIR = os.path.join(os.path.dirname(__file__), "recipes")

OS_BASELINES = {
    "ubuntu-26.04": {
        "os_min_ram_mb": 512,
        "os_min_cpu_cores": 1,
        "os_min_disk_mb": 5120
    }
}

def load_recipes():
    recipes = {}
    for path in glob.glob(os.path.join(RECIPES_DIR, "*.yaml")):
        with open(path) as f:
            r = yaml.safe_load(f)
            recipes[r["id"]] = r
    return recipes

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/api/catalogue")
def catalogue():
    recipes = load_recipes()
    category = request.args.get("category")
    apps = list(recipes.values())
    if category:
        apps = [a for a in apps if category in a.get("categories", [])]
    return jsonify({
        "os_baselines": OS_BASELINES,
        "applications": apps,
        "total": len(apps)
    })

@app.route("/api/compose", methods=["POST"])
def compose():
    data = request.get_json(force=True)
    recipes = load_recipes()

    selected = data.get("applications", [])
    credentials = data.get("credentials", {})
    base_domain = data.get("base_domain", "example.stratoserver.net")
    base_os = data.get("base_os", "ubuntu-26.04")

    # Validation
    errors = []
    seen_ids = set()
    for item in selected:
        app_id = item.get("id")
        if app_id in seen_ids:
            errors.append({"code": "duplicate_application", "app": app_id})
        seen_ids.add(app_id)
        if app_id not in recipes:
            errors.append({"code": "recipe_not_found", "app": app_id})
            continue
        recipe = recipes[app_id]
        if base_os not in recipe.get("supported_os", []):
            errors.append({"code": "os_not_supported", "app": app_id})

    # Incompatibility check
    selected_ids = [item["id"] for item in selected if item["id"] in recipes]
    for app_id in selected_ids:
        for incompat in recipes[app_id].get("incompatible_with_apps", []):
            if incompat in selected_ids:
                errors.append({"code": "incompatible_applications", "apps": [app_id, incompat]})

    # Parameter validation
    field_errors = []
    for item in selected:
        app_id = item.get("id")
        if app_id not in recipes:
            continue
        recipe = recipes[app_id]
        params = item.get("parameters", {})
        for p in recipe.get("parameters", []):
            if p.get("required") and not p.get("auto_generate"):
                # APP_DOMAIN is generated by the backend, skip required check
                if p["name"] == "APP_DOMAIN":
                    continue
                val = params.get(p["name"], "")
                if not val or not val.strip():
                    field_errors.append({
                        "app": app_id,
                        "field": p["name"],
                        "message": f"{p['display_name']} is required"
                    })

    if errors or field_errors:
        return jsonify({
            "error": "validation_error",
            "message": "Request validation failed",
            "details": {"errors": errors, "field_errors": field_errors}
        }), 422

    # Build resolved parameters (auto-generate where needed)
    resolved = {}
    http_routes = []
    direct_ports = []

    for item in selected:
        app_id = item["id"]
        recipe = recipes[app_id]
        app_params = item.get("parameters", {}).copy()

        # Auto-generate APP_DOMAIN from app_id + base_domain
        for p in recipe.get("parameters", []):
            if p["name"] == "APP_DOMAIN" and not app_params.get("APP_DOMAIN"):
                subdomain = app_id.replace("-", "")
                app_params["APP_DOMAIN"] = f"{subdomain}.{base_domain}"

        for p in recipe.get("parameters", []):
            pname = p["name"]
            if not app_params.get(pname) and p.get("auto_generate"):
                app_params[pname] = secrets.token_urlsafe(24)
            if not app_params.get(pname) and p.get("default"):
                app_params[pname] = p["default"]

        resolved[app_id] = app_params

        # Determine routes
        for port in recipe.get("ports", []):
            if port["public"] and port["port"] in (80, 443, 5678, 9443, 11434, 18789):
                subdomain = app_id.replace("-", "")
                http_routes.append({
                    "application": app_id,
                    "url": f"https://{subdomain}.{base_domain}"
                })
            elif port["public"]:
                direct_ports.append({
                    "application": app_id,
                    "port": port["port"],
                    "protocol": port["protocol"],
                    "description": port["description"]
                })

    # Generate cloud-init
    cloud_init = _generate_cloud_init(selected_ids, resolved, recipes, base_domain, credentials)

    token = secrets.token_urlsafe(32)

    return jsonify({
        "token": token,
        "expires_at": "2026-04-22T16:00:00Z",
        "cloud_init": cloud_init,
        "network": {
            "traefik_enabled": True,
            "http_routes": http_routes,
            "direct_ports": direct_ports
        },
        "resolved_parameters": resolved
    })

def _generate_cloud_init(app_ids, resolved, recipes, base_domain, credentials):
    apps_yaml = []
    for app_id in app_ids:
        params = resolved.get(app_id, {})
        param_lines = "\n".join(f"      {k}: {v}" for k, v in params.items())
        if param_lines:
            apps_yaml.append(f"    - id: {app_id}\n      parameters:\n{param_lines}")
        else:
            apps_yaml.append(f"    - id: {app_id}")

    apps_block = "\n".join(apps_yaml)
    root_pw = credentials.get("root_password", "CHANGE_ME")
    ssh_key = credentials.get("ssh_public_key", "")
    ssh_block = f"\n  - {ssh_key}" if ssh_key else ""
    bootstrap_token = secrets.token_urlsafe(32)

    lines = [
        "#cloud-config",
        "# Generated by Application Factory PoC",
        "# Target OS: Ubuntu 26.04 LTS + Docker Engine",
        "",
        "hostname: af-server",
        "",
        "users:",
        "  - name: root",
        "    lock_passwd: false",
        f"    hashed_passwd: \"$(echo '{root_pw}' | openssl passwd -6 -stdin)\"",
        f"    ssh_authorized_keys:{ssh_block}",
        "",
        "runcmd:",
        "  - apt-get update -q",
        "  - apt-get install -y -q docker.io docker-compose-v2 curl",
        "  - systemctl enable --now docker",
        "  - |",
        f"    AF_BOOTSTRAP_TOKEN=\"{bootstrap_token}\"",
        "    curl -fsSL \"https://af-api.example.com/bootstrap\" \\",
        "      -H \"Content-Type: application/json\" \\",
        "      -d '{\"token\": \"'\"$AF_BOOTSTRAP_TOKEN\"'\"}' \\",
        "      | bash",
        "",
        "# Applications to install:",
        apps_block,
        "",
        f"# Base domain: {base_domain}",
    ]
    return "\n".join(lines) + "\n"

@app.route("/api/simulate-bootstrap", methods=["POST"])
def simulate_bootstrap():
    """Server-Sent Events: simulierter Installationslog"""
    data = request.get_json(force=True)
    app_ids = data.get("app_ids", [])
    recipes = load_recipes()

    def generate():
        import time

        steps = [
            ("info", "🚀 Application Factory Bootstrap started"),
            ("info", "📦 Updating package lists..."),
            ("cmd",  "apt-get update -q"),
            ("ok",   "Package lists updated"),
            ("info", "🐳 Installing Docker Engine..."),
            ("cmd",  "apt-get install -y docker.io docker-compose-v2"),
            ("ok",   "Docker 26.1.3 installed"),
            ("cmd",  "systemctl enable --now docker"),
            ("ok",   "Docker daemon started"),
            ("info", "🔧 Installing Traefik reverse proxy..."),
            ("cmd",  "docker pull traefik:v3.0"),
            ("ok",   "Traefik ready"),
        ]

        for app_id in app_ids:
            recipe = recipes.get(app_id, {})
            display = recipe.get("display_name", app_id)
            version = recipe.get("app_version", "latest")
            steps += [
                ("info",  f"📥 Deploying {display} v{version}..."),
                ("cmd",   f"mkdir -p /opt/{app_id}"),
                ("cmd",   f"docker compose -f /opt/{app_id}/docker-compose.yml up -d"),
                ("ok",    f"{display} started successfully"),
            ]
            for port in recipe.get("ports", []):
                if port.get("public"):
                    steps.append(("url", f"  → {display}: port {port['port']}/tcp ({port['description']})"))

        steps += [
            ("info", "✅ All applications deployed"),
            ("info", "🌐 Traefik routing configured"),
            ("done", "🎉 Bootstrap complete!"),
        ]

        for level, msg in steps:
            yield f"data: {level}|{msg}\n\n"
            time.sleep(0.3 if level in ("cmd", "ok") else 0.6)

    return Response(generate(), mimetype="text/event-stream",
                    headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})

if __name__ == "__main__":
    app.run(debug=True, port=5050)
